spring:
  application:
    name: aop
  datasource:
    url: {  }
    username: {  }
    password: {  }
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  mail:
    host: smtp.mail.ru
    port: 587
    username: {  }
    password: {  }
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

notification:
  email:
    recipient: {  }
    sender: {  }
    subject-update: Task Status Update
    basic-text-update: The task has changed status

kafka:
  bootstrap-servers: {  }
  producer:
    retries: 3
  consumer:
    group-id: task-group
    auto-offset-reset: earliest
    enable-auto-commit: false
    trusted-packages: net.az3l1t.aop.dto.kafka
  listener:
    concurrency: 3
    ack-mode: MANUAL_IMMEDIATE
    backoff-interval: 1000
    backoff-max-attempts: 3
  topics:
    task-updating: task-updating-topic

async:
  notification:
    core-pool-size: 4
    max-pool-size: 8
    queue-capacity: 100
    thread-name-prefix: "NotificationExecutor-"

execution:
  time:
    cracking: 500

server:
  port: {  }